apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    version: v1
    app: ubuntu-sshd
  name: ubuntu-sshd
  namespace: default
spec:
  revisionHistoryLimit: 5
  replicas: 1
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"john", "value":"tenant"}]'
      labels:
        app: ubuntu-sshd
    spec:
      containers:
      - name: ubuntu-sshd
        image: rastasheep/ubuntu-sshd:14.04
        imagePullPolicy: Always
