kind: Role
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: default-ns-admin
  namespace: default
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: RoleBinding
metadata:
  name: default-ns-admin
  namespace: default
subjects:
- kind: User
  name: john
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: default-ns-admin
