kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: server-components
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
# 1 ClusterRoleBinding should be created for every worker node in the cluster
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRoleBinding
metadata:
  name: kubelet-192.168.255.10
subjects:
- kind: User
  name: 192.168.255.10 # Kubelet certificate CN name.
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: server-components
# ---
# apiVersion: rbac.authorization.k8s.io/v1alpha1
# kind: ClusterRoleBinding
# metadata:
#   name: kubelet-10.9.8.6
# subjects:
# - kind: User
#   name: 10.9.8.6 # Kubelet certificate CN name.
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: server-components
# ---
# apiVersion: rbac.authorization.k8s.io/v1alpha1
# kind: ClusterRoleBinding
# metadata:
#   name: kubelet-10.9.8.5
# subjects:
# - kind: User
#   name: 10.9.8.5 # Kubelet certificate CN name.
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: server-components
